api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/JobBoard/Infrastructure/Config/Http']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
